### ISSUE TITLE
Code Review: @GAstraeus

### ISSUE THREAD

**Issue by GAstraeus** [RD345/CS435-Project-2#2]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graph.py#L35

node1 and node 2 should already be nodes running getNode on them is redundant

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graph.py#L45
If you use a set you can prevent yourself from having to traverse through every node and directly access the object through the set API

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graph.py#L57
If this function is unused I suggest deleting it to increase clarity and help clearly define what this class is/does

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/weightedGraph.py#L4
I dont think you need these comments they reference the question numbers and do not do much in further explaining what is in the code.

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/gridGraph.py#L27
Instead of having your code throw an error - you can check the bounds yourself before adding the node.

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/gridGraph.py#L19
Consider adding n (num nodes) as an initialization parameter here it will help with bounds checking later.

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L13
This type of encapsulation could be confusing for someone not familiar with python. Declaring this as a private routine will make clarity better and accomplish the same goal.

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/node.py#L9
used in:
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L21

By having visited as a member of a node if you want to reset it you need to run an O(n) routine. If you make a visited set you can easily check if it is visited without having to clear or duplicate objects if you want to run a search more than once on the same graph.

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L60
and 
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L112

You should return None or empty lst if the path was not found. False is a different type and could cause unreasonable effects in handling the different types of outputs.

**Comment by GAstraeus** [comment]
https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/gridGraph.py#L36
Creating a contains routine for check if a node is already connected will help eliminate all of this.

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graph.py#L35
> 
> node1 and node 2 should already be nodes running getNode on them is redundant

If this function were to take in exclusively nodes, this would be entirely redundant, exactly as you said. However, all of the functions that add edges are setup so that they can take inputs in the forms of nodes, strings, or integers, and this line ensures that that input is then converted to a Node before the function is called, thus preventing the function from crashing with invalid types.

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graph.py#L45
> 
> 
> If you use a set you can prevent yourself from having to traverse through every node and directly access the object through the set API

Can you explain how is this would be possible? Everything I looked into said that sets cannot be accessed by index or slice, so looping through the elements would still be necessary. I have since modified some of my functions to return sets, however I have not changed the base type as I see no benefit that I'm aware of.

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graph.py#L57
> 
> 
> If this function is unused I suggest deleting it to increase clarity and help clearly define what this class is/does

OK - I tweaked the usage of the function and updated the description to match in [this commit.](1fb4a8f359ab30e15683d665b1904e54d1b439b8)

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/weightedGraph.py#L4
> 
> 
> I dont think you need these comments they reference the question numbers and do not do much in further explaining what is in the code.

These comments are important to me because they remind me of what the intention of the methods is supposed to be. They also mark which functions are ones that are requirements vs which are ones I made myself, either for increased functionality or use in the required method.

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/gridGraph.py#L27
> 
> 
> Instead of having your code throw an error - you can check the bounds yourself before adding the node.

You are completely right about this, I will have this just check the index instead of catching the exception. Done [here](https://github.com/RD345/CS435-Project-2/commit/de5fafe4dcfea15de4df459d63fdd7d698d92051)

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/gridGraph.py#L19
> 
> 
> Consider adding n (num nodes) as an initialization parameter here it will help with bounds checking later.

This is a good idea, although I'm not sure how much I will actually use it at this point. Added in [this commit](https://github.com/RD345/CS435-Project-2/commit/de5fafe4dcfea15de4df459d63fdd7d698d92051)

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L13
> 
> 
> This type of encapsulation could be confusing for someone not familiar with python. Declaring this as a private routine will make clarity better and accomplish the same goal.

OK - Done in [this commit](https://github.com/RD345/CS435-Project-2/commit/d42aff77187d88e5e2438aee6117bb8f9e093d15)

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/node.py#L9
> 
> 
> used in:
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L21
> 
> By having visited as a member of a node if you want to reset it you need to run an O(n) routine. If you make a visited set you can easily check if it is visited without having to clear or duplicate objects if you want to run a search more than once on the same graph.

Actually, using this method, while it creates a linear reset routine, it actually is faster overall, as the method(s) do not have to search through a visited set/list every time, but can check the node itself in constant time. This reduces the complexity from O(n log n) to just O(n).

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L60
> 
> 
> and
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/graphSearch.py#L112
> 
> You should return None or empty lst if the path was not found. False is a different type and could cause unreasonable effects in handling the different types of outputs.

OK - Will be done in next commit. Edit: Done [here](https://github.com/RD345/CS435-Project-2/commit/672570869c3e260b0433d731c9feb3ea7c4f1293)

**Comment by RD345** [comment]
> https://github.com/RD345/CS435-Project-2/blob/a753733ce69be4aad077d74afcd958edf9ec0acf/gridGraph.py#L36
> 
> 
> Creating a contains routine for check if a node is already connected will help eliminate all of this.

Creating a method to check would still require doing these comparisons, and since this is only done once throughout the class, making a method to do so would be adding lines for no discernable reason.

**Comment by RD345** [comment]
All points have now been addressed.
